// Code generated by Lettermint SDK generator; DO NOT EDIT.

package lettermint

type MessageStatus string

const (
	MessageStatusScheduled      MessageStatus = "scheduled"
	MessageStatusPending        MessageStatus = "pending"
	MessageStatusQueued         MessageStatus = "queued"
	MessageStatusQuarantined    MessageStatus = "quarantined"
	MessageStatusSuppressed     MessageStatus = "suppressed"
	MessageStatusProcessed      MessageStatus = "processed"
	MessageStatusDelivered      MessageStatus = "delivered"
	MessageStatusOpened         MessageStatus = "opened"
	MessageStatusClicked        MessageStatus = "clicked"
	MessageStatusSoftBounced    MessageStatus = "soft_bounced"
	MessageStatusHardBounced    MessageStatus = "hard_bounced"
	MessageStatusSpamComplaint  MessageStatus = "spam_complaint"
	MessageStatusFailed         MessageStatus = "failed"
	MessageStatusBlocked        MessageStatus = "blocked"
	MessageStatusPolicyRejected MessageStatus = "policy_rejected"
	MessageStatusUnsubscribed   MessageStatus = "unsubscribed"
	MessageStatusCanceled       MessageStatus = "canceled"
)

type SendMailRequest struct {
	Route       string                   `json:"route,omitempty"`
	From        string                   `json:"from"`
	To          []string                 `json:"to"`
	Cc          []string                 `json:"cc,omitempty"`
	Bcc         []string                 `json:"bcc,omitempty"`
	ReplyTo     []string                 `json:"reply_to,omitempty"`
	Subject     string                   `json:"subject"`
	ScheduledAt *string                  `json:"scheduled_at,omitempty"`
	Headers     map[string]string        `json:"headers,omitempty"`
	Metadata    map[string]string        `json:"metadata,omitempty"`
	Tag         *string                  `json:"tag,omitempty"`
	Tags        []map[string]interface{} `json:"tags,omitempty"`
	Settings    map[string]interface{}   `json:"settings,omitempty"`
	HTML        *string                  `json:"html,omitempty"`
	Text        *string                  `json:"text,omitempty"`
	Attachments []map[string]interface{} `json:"attachments,omitempty"`
}

type SendBatchMailRequest []SendMailRequest

type TlsPolicy string

const (
	TlsPolicyOpportunistic TlsPolicy = "opportunistic"
	TlsPolicyEnforced      TlsPolicy = "enforced"
)

type AttachmentDelivery string

const (
	AttachmentDeliveryInline AttachmentDelivery = "inline"
	AttachmentDeliveryURL    AttachmentDelivery = "url"
)

type BuiltInTeamRole string

const (
	BuiltInTeamRoleOwner  BuiltInTeamRole = "owner"
	BuiltInTeamRoleAdmin  BuiltInTeamRole = "admin"
	BuiltInTeamRoleMember BuiltInTeamRole = "member"
)

type CursorPaginator struct {
	Data        []string `json:"data"`
	Path        *string  `json:"path"`
	PerPage     int      `json:"per_page"`
	NextCursor  *string  `json:"next_cursor"`
	NextPageURL *string  `json:"next_page_url"`
	PrevCursor  *string  `json:"prev_cursor"`
	PrevPageURL *string  `json:"prev_page_url"`
}

type DkimMode string

const (
	DkimModeLegacyTxt    DkimMode = "legacy_txt"
	DkimModeManagedCname DkimMode = "managed_cname"
)

type DnsRecordPurpose string

const (
	DnsRecordPurposeReturnPath    DnsRecordPurpose = "return_path"
	DnsRecordPurposeDmarc         DnsRecordPurpose = "dmarc"
	DnsRecordPurposeDkimLegacy    DnsRecordPurpose = "dkim_legacy"
	DnsRecordPurposeDkimPrimary   DnsRecordPurpose = "dkim_primary"
	DnsRecordPurposeDkimSecondary DnsRecordPurpose = "dkim_secondary"
)

type DnsRecordStatus string

const (
	DnsRecordStatusActive  DnsRecordStatus = "active"
	DnsRecordStatusFailed  DnsRecordStatus = "failed"
	DnsRecordStatusPending DnsRecordStatus = "pending"
)

type DnsVerificationScope string

const (
	DnsVerificationScopeRequired    DnsVerificationScope = "required"
	DnsVerificationScopeRecommended DnsVerificationScope = "recommended"
	DnsVerificationScopeMigration   DnsVerificationScope = "migration"
	DnsVerificationScopeDeprecated  DnsVerificationScope = "deprecated"
)

type DomainData struct {
	ID              string                   `json:"id"`
	Domain          string                   `json:"domain"`
	DkimMode        DkimMode                 `json:"dkim_mode"`
	RotationReady   bool                     `json:"rotation_ready"`
	StatusChangedAt *string                  `json:"status_changed_at"`
	DNSRecords      []DomainDnsRecordData    `json:"dns_records,omitempty"`
	Projects        []map[string]interface{} `json:"projects,omitempty"`
	CreatedAt       string                   `json:"created_at"`
}

type DomainDnsRecordData struct {
	ID                      string               `json:"id"`
	Type                    RecordType           `json:"type"`
	Hostname                string               `json:"hostname"`
	Fqdn                    string               `json:"fqdn"`
	Content                 string               `json:"content"`
	Status                  DnsRecordStatus      `json:"status"`
	Purpose                 DnsRecordPurpose     `json:"purpose"`
	VerificationScope       DnsVerificationScope `json:"verification_scope"`
	RequiredForVerification bool                 `json:"required_for_verification"`
	VerifiedAt              *string              `json:"verified_at"`
	LastCheckedAt           *string              `json:"last_checked_at"`
}

type DomainListData struct {
	ID              string       `json:"id"`
	Domain          string       `json:"domain"`
	Status          DomainStatus `json:"status"`
	DkimMode        DkimMode     `json:"dkim_mode"`
	StatusChangedAt *string      `json:"status_changed_at"`
	CreatedAt       string       `json:"created_at"`
}

type DomainStatus string

const (
	DomainStatusVerified            DomainStatus = "verified"
	DomainStatusPartiallyVerified   DomainStatus = "partially_verified"
	DomainStatusPendingVerification DomainStatus = "pending_verification"
	DomainStatusFailedVerification  DomainStatus = "failed_verification"
)

type InitialRoutes string

const (
	InitialRoutesBoth          InitialRoutes = "both"
	InitialRoutesTransactional InitialRoutes = "transactional"
	InitialRoutesBroadcast     InitialRoutes = "broadcast"
)

type MessageAttachmentData struct {
	Size        int     `json:"size"`
	Filename    string  `json:"filename"`
	ContentID   *string `json:"content_id"`
	ContentType string  `json:"content_type"`
}

type MessageData struct {
	ID              string                   `json:"id"`
	Type            MessageType              `json:"type"`
	Status          MessageStatus            `json:"status"`
	StatusChangedAt *string                  `json:"status_changed_at"`
	ScheduledAt     *string                  `json:"scheduled_at"`
	Tag             *string                  `json:"tag"`
	Tags            []map[string]interface{} `json:"tags"`
	FromEmail       string                   `json:"from_email"`
	FromName        *string                  `json:"from_name"`
	ReplyTo         []string                 `json:"reply_to"`
	Subject         *string                  `json:"subject"`
	To              []MessageRecipientData   `json:"to"`
	Cc              []MessageRecipientData   `json:"cc"`
	Bcc             []MessageRecipientData   `json:"bcc"`
	Attachments     []MessageAttachmentData  `json:"attachments"`
	Metadata        map[string]string        `json:"metadata"`
	SpamScore       *float64                 `json:"spam_score,omitempty"`
	SpamSymbols     []SpamSymbol             `json:"spam_symbols,omitempty"`
	RouteID         string                   `json:"route_id"`
	CreatedAt       string                   `json:"created_at"`
}

type MessageEventData struct {
	MessageID string                   `json:"message_id"`
	Event     MessageEventType         `json:"event"`
	Tag       *string                  `json:"tag"`
	Tags      []map[string]interface{} `json:"tags"`
	Metadata  map[string]interface{}   `json:"metadata"`
	Timestamp string                   `json:"timestamp"`
}

type MessageEventType string

const (
	MessageEventTypeScheduled          MessageEventType = "scheduled"
	MessageEventTypeRescheduled        MessageEventType = "rescheduled"
	MessageEventTypeCanceled           MessageEventType = "canceled"
	MessageEventTypeReleased           MessageEventType = "released"
	MessageEventTypeQueued             MessageEventType = "queued"
	MessageEventTypeProcessed          MessageEventType = "processed"
	MessageEventTypeSuppressed         MessageEventType = "suppressed"
	MessageEventTypeDelivered          MessageEventType = "delivered"
	MessageEventTypeAutoReplied        MessageEventType = "auto_replied"
	MessageEventTypeSoftBounced        MessageEventType = "soft_bounced"
	MessageEventTypeHardBounced        MessageEventType = "hard_bounced"
	MessageEventTypeSpamComplaint      MessageEventType = "spam_complaint"
	MessageEventTypeFailed             MessageEventType = "failed"
	MessageEventTypeBlocked            MessageEventType = "blocked"
	MessageEventTypePolicyRejected     MessageEventType = "policy_rejected"
	MessageEventTypeUnsubscribed       MessageEventType = "unsubscribed"
	MessageEventTypeOpened             MessageEventType = "opened"
	MessageEventTypeClicked            MessageEventType = "clicked"
	MessageEventTypeInboundReceived    MessageEventType = "inbound_received"
	MessageEventTypeInboundQueued      MessageEventType = "inbound_queued"
	MessageEventTypeInboundSpamBlocked MessageEventType = "inbound_spam_blocked"
	MessageEventTypeInboundReleased    MessageEventType = "inbound_released"
	MessageEventTypeInboundProcessed   MessageEventType = "inbound_processed"
	MessageEventTypeInboundRetry       MessageEventType = "inbound_retry"
)

type MessageListData struct {
	ID              string                   `json:"id"`
	Type            MessageType              `json:"type"`
	Status          MessageStatus            `json:"status"`
	ScheduledAt     *string                  `json:"scheduled_at"`
	SpamScore       *float64                 `json:"spam_score,omitempty"`
	FromEmail       string                   `json:"from_email"`
	FromName        *string                  `json:"from_name"`
	Subject         *string                  `json:"subject"`
	To              []MessageRecipientData   `json:"to"`
	Cc              []MessageRecipientData   `json:"cc"`
	Bcc             []MessageRecipientData   `json:"bcc"`
	ReplyTo         []string                 `json:"reply_to"`
	Tag             *string                  `json:"tag"`
	Tags            []map[string]interface{} `json:"tags"`
	StatusChangedAt *string                  `json:"status_changed_at"`
	CreatedAt       string                   `json:"created_at"`
}

type RescheduleMessageRequest struct {
	ScheduledAt string `json:"scheduled_at"`
}

type MessageScheduleResponse struct {
	MessageID   string         `json:"message_id"`
	Status      *MessageStatus `json:"status"`
	ScheduledAt *string        `json:"scheduled_at"`
}

type MessageRecipientData struct {
	Email string  `json:"email"`
	Name  *string `json:"name"`
}

type MessageStatsData struct {
	MessagesTransactional int     `json:"messages_transactional"`
	MessagesBroadcast     int     `json:"messages_broadcast"`
	MessagesInbound       int     `json:"messages_inbound"`
	Deliverability        float64 `json:"deliverability"`
}

type MessageType string

const (
	MessageTypeInbound  MessageType = "inbound"
	MessageTypeOutbound MessageType = "outbound"
)

type Plan string

const (
	PlanFree    Plan = "free"
	PlanStarter Plan = "starter"
	PlanGrowth  Plan = "growth"
	PlanPro     Plan = "pro"
)

type ProjectAccessScope string

const (
	ProjectAccessScopeAll      ProjectAccessScope = "all"
	ProjectAccessScopeSelected ProjectAccessScope = "selected"
)

type ProjectData struct {
	ID                 string            `json:"id"`
	Name               string            `json:"name"`
	SMTPEnabled        bool              `json:"smtp_enabled"`
	RedactEmailContent bool              `json:"redact_email_content"`
	DefaultRouteID     *string           `json:"default_route_id"`
	TokenGeneratedAt   *string           `json:"token_generated_at"`
	TokenLastUsedAt    *string           `json:"token_last_used_at"`
	TokenLastUsedIp    *string           `json:"token_last_used_ip"`
	Routes             []RouteData       `json:"routes,omitempty"`
	RoutesCount        int               `json:"routes_count,omitempty"`
	Domains            []DomainData      `json:"domains,omitempty"`
	DomainsCount       int               `json:"domains_count,omitempty"`
	Last28Days         *MessageStatsData `json:"last_28_days,omitempty"`
	CreatedAt          string            `json:"created_at"`
	UpdatedAt          string            `json:"updated_at"`
}

type ProjectListData struct {
	ID           string           `json:"id"`
	Name         string           `json:"name"`
	SMTPEnabled  bool             `json:"smtp_enabled"`
	RoutesCount  int              `json:"routes_count"`
	DomainsCount int              `json:"domains_count"`
	Last28Days   MessageStatsData `json:"last_28_days"`
	CreatedAt    string           `json:"created_at"`
	UpdatedAt    string           `json:"updated_at"`
}

type RbacConflictCode string

const (
	RbacConflictCodeStaleResource         RbacConflictCode = "stale_resource"
	RbacConflictCodeOwnerProtected        RbacConflictCode = "owner_protected"
	RbacConflictCodeLastOwner             RbacConflictCode = "last_owner"
	RbacConflictCodeBuiltInRoleImmutable  RbacConflictCode = "built_in_role_immutable"
	RbacConflictCodeCustomRoleRequiresPro RbacConflictCode = "custom_role_requires_pro"
)

type RbacPermission string

const (
	RbacPermissionTeamManage             RbacPermission = "team:manage"
	RbacPermissionBillingManage          RbacPermission = "billing:manage"
	RbacPermissionSecurityManage         RbacPermission = "security:manage"
	RbacPermissionAuditRead              RbacPermission = "audit:read"
	RbacPermissionSupportManage          RbacPermission = "support:manage"
	RbacPermissionMembersRead            RbacPermission = "members:read"
	RbacPermissionMembersManage          RbacPermission = "members:manage"
	RbacPermissionRolesManage            RbacPermission = "roles:manage"
	RbacPermissionTeamTokensRead         RbacPermission = "team_tokens:read"
	RbacPermissionTeamTokensManage       RbacPermission = "team_tokens:manage"
	RbacPermissionTeamTokensRotate       RbacPermission = "team_tokens:rotate"
	RbacPermissionTeamTokensRevoke       RbacPermission = "team_tokens:revoke"
	RbacPermissionProjectsCreate         RbacPermission = "projects:create"
	RbacPermissionTeamSuppressionsRead   RbacPermission = "team_suppressions:read"
	RbacPermissionTeamSuppressionsAdd    RbacPermission = "team_suppressions:add"
	RbacPermissionTeamSuppressionsRemove RbacPermission = "team_suppressions:remove"
	RbacPermissionProjectsRead           RbacPermission = "projects:read"
	RbacPermissionProjectsManage         RbacPermission = "projects:manage"
	RbacPermissionProjectsDelete         RbacPermission = "projects:delete"
	RbacPermissionRoutesRead             RbacPermission = "routes:read"
	RbacPermissionRoutesManage           RbacPermission = "routes:manage"
	RbacPermissionRoutesDelete           RbacPermission = "routes:delete"
	RbacPermissionDomainsRead            RbacPermission = "domains:read"
	RbacPermissionDomainsManage          RbacPermission = "domains:manage"
	RbacPermissionDomainsDelete          RbacPermission = "domains:delete"
	RbacPermissionProjectTokensRead      RbacPermission = "project_tokens:read"
	RbacPermissionProjectTokensManage    RbacPermission = "project_tokens:manage"
	RbacPermissionProjectTokensRotate    RbacPermission = "project_tokens:rotate"
	RbacPermissionProjectTokensRevoke    RbacPermission = "project_tokens:revoke"
	RbacPermissionWebhooksRead           RbacPermission = "webhooks:read"
	RbacPermissionWebhooksManage         RbacPermission = "webhooks:manage"
	RbacPermissionWebhooksDelete         RbacPermission = "webhooks:delete"
	RbacPermissionWebhooksRotateSecret   RbacPermission = "webhooks:rotate_secret"
	RbacPermissionStatsRead              RbacPermission = "stats:read"
	RbacPermissionMessagesRead           RbacPermission = "messages:read"
	RbacPermissionMessagesReadContent    RbacPermission = "messages:read_content"
	RbacPermissionMessagesSend           RbacPermission = "messages:send"
	RbacPermissionSuppressionsRead       RbacPermission = "suppressions:read"
	RbacPermissionSuppressionsAdd        RbacPermission = "suppressions:add"
	RbacPermissionSuppressionsRemove     RbacPermission = "suppressions:remove"
)

type RecordType string

const (
	RecordTypeTXT   RecordType = "TXT"
	RecordTypeCNAME RecordType = "CNAME"
	RecordTypeMX    RecordType = "MX"
)

type RouteData struct {
	ID                        string                 `json:"id"`
	ProjectID                 string                 `json:"project_id"`
	Slug                      string                 `json:"slug"`
	Name                      string                 `json:"name"`
	RouteType                 RouteType              `json:"route_type"`
	IsDefault                 bool                   `json:"is_default"`
	InboundAddress            *string                `json:"inbound_address,omitempty"`
	InboundDomain             *string                `json:"inbound_domain,omitempty"`
	InboundDomainVerifiedAt   *string                `json:"inbound_domain_verified_at,omitempty"`
	InboundSpamThreshold      *float64               `json:"inbound_spam_threshold,omitempty"`
	AttachmentDelivery        AttachmentDelivery     `json:"attachment_delivery,omitempty"`
	Settings                  map[string]interface{} `json:"settings,omitempty"`
	Project                   ProjectData            `json:"project,omitempty"`
	WebhooksCount             int                    `json:"webhooks_count,omitempty"`
	SuppressedRecipientsCount int                    `json:"suppressed_recipients_count,omitempty"`
	Statistics                []RouteStatisticData   `json:"statistics,omitempty"`
	CreatedAt                 string                 `json:"created_at"`
	UpdatedAt                 string                 `json:"updated_at"`
}

type RouteListData struct {
	ID                        string    `json:"id"`
	Slug                      string    `json:"slug"`
	Name                      string    `json:"name"`
	RouteType                 RouteType `json:"route_type"`
	IsDefault                 bool      `json:"is_default"`
	WebhooksCount             int       `json:"webhooks_count"`
	SuppressedRecipientsCount int       `json:"suppressed_recipients_count"`
	CreatedAt                 string    `json:"created_at"`
	UpdatedAt                 string    `json:"updated_at"`
}

type RouteStatisticData struct {
	Date                 string `json:"date"`
	SentCount            int    `json:"sent_count"`
	DeliveredCount       int    `json:"delivered_count"`
	OpenedCount          int    `json:"opened_count"`
	ClickedCount         int    `json:"clicked_count"`
	HardBounceCount      int    `json:"hard_bounce_count"`
	SpamComplaintCount   int    `json:"spam_complaint_count"`
	InboundReceivedCount int    `json:"inbound_received_count"`
	ObservedOpenedCount  *int   `json:"observed_opened_count,omitempty"`
	HumanOpenedCount     *int   `json:"human_opened_count,omitempty"`
	PrivacyOpenedCount   *int   `json:"privacy_opened_count,omitempty"`
	EffectiveOpenedCount *int   `json:"effective_opened_count"`
	MachineOpenedCount   *int   `json:"machine_opened_count"`
	MachineClickedCount  *int   `json:"machine_clicked_count"`
}

type RouteType string

const (
	RouteTypeTransactional RouteType = "transactional"
	RouteTypeBroadcast     RouteType = "broadcast"
	RouteTypeInbound       RouteType = "inbound"
)

type SpamSymbol struct {
	Name        string   `json:"name"`
	Score       float64  `json:"score"`
	Options     []string `json:"options"`
	Description *string  `json:"description"`
}

type StatsDailyData struct {
	Date            string           `json:"date"`
	Sent            int              `json:"sent"`
	Delivered       int              `json:"delivered"`
	HardBounced     int              `json:"hard_bounced"`
	SpamComplaints  int              `json:"spam_complaints"`
	Opened          *int             `json:"opened"`
	Clicked         *int             `json:"clicked"`
	Inbound         StatsInboundData `json:"inbound"`
	Transactional   *StatsTypeData   `json:"transactional"`
	Broadcast       *StatsTypeData   `json:"broadcast"`
	ObservedOpened  *int             `json:"observed_opened,omitempty"`
	HumanOpened     *int             `json:"human_opened,omitempty"`
	PrivacyOpened   *int             `json:"privacy_opened,omitempty"`
	EffectiveOpened *int             `json:"effective_opened"`
	MachineOpened   *int             `json:"machine_opened"`
	MachineClicked  *int             `json:"machine_clicked"`
}

type StatsData struct {
	From   string           `json:"from"`
	To     string           `json:"to"`
	Totals StatsTotalsData  `json:"totals"`
	Daily  []StatsDailyData `json:"daily"`
}

type StatsInboundData struct {
	Received int `json:"received"`
}

type StatsRequestData struct {
	From           string  `json:"from"`
	To             string  `json:"to"`
	ProjectID      *string `json:"project_id,omitempty"`
	IncludeMachine *bool   `json:"include_machine,omitempty"`
}

type StatsTotalsData struct {
	Sent            int              `json:"sent"`
	Delivered       int              `json:"delivered"`
	HardBounced     int              `json:"hard_bounced"`
	SpamComplaints  int              `json:"spam_complaints"`
	Opened          *int             `json:"opened"`
	Clicked         *int             `json:"clicked"`
	Inbound         StatsInboundData `json:"inbound"`
	Transactional   *StatsTypeData   `json:"transactional"`
	Broadcast       *StatsTypeData   `json:"broadcast"`
	ObservedOpened  *int             `json:"observed_opened,omitempty"`
	HumanOpened     *int             `json:"human_opened,omitempty"`
	PrivacyOpened   *int             `json:"privacy_opened,omitempty"`
	EffectiveOpened *int             `json:"effective_opened"`
	MachineOpened   *int             `json:"machine_opened"`
	MachineClicked  *int             `json:"machine_clicked"`
}

type StatsTypeData struct {
	Sent           int `json:"sent"`
	HardBounced    int `json:"hard_bounced"`
	SpamComplaints int `json:"spam_complaints"`
}

type StoreDomainData struct {
	Domain string `json:"domain"`
}

type StoreProjectData struct {
	Name          string        `json:"name"`
	SMTPEnabled   *bool         `json:"smtp_enabled,omitempty"`
	InitialRoutes InitialRoutes `json:"initial_routes,omitempty"`
	ShortToken    *bool         `json:"short_token,omitempty"`
}

type StoreRouteData struct {
	Name      string    `json:"name"`
	RouteType RouteType `json:"route_type"`
	Slug      *string   `json:"slug,omitempty"`
}

type StoreSuppressionData struct {
	Email     *string           `json:"email,omitempty"`
	Emails    []string          `json:"emails,omitempty"`
	Reason    SuppressionReason `json:"reason"`
	Scope     SuppressionScope  `json:"scope"`
	RouteID   *string           `json:"route_id,omitempty"`
	ProjectID *string           `json:"project_id,omitempty"`
}

type StoreWebhookData struct {
	RouteID              string            `json:"route_id"`
	Name                 string            `json:"name"`
	URL                  string            `json:"url"`
	Events               []APIWebhookEvent `json:"events"`
	Enabled              *bool             `json:"enabled,omitempty"`
	IncludeMachineEvents *bool             `json:"include_machine_events,omitempty"`
}

type SuppressedRecipientData struct {
	ID            string                        `json:"id"`
	Type          SuppressionType               `json:"type"`
	Value         string                        `json:"value"`
	Reason        SuppressionReason             `json:"reason"`
	Scope         SuppressionScope              `json:"scope"`
	ProjectID     *string                       `json:"project_id"`
	RouteID       *string                       `json:"route_id"`
	SourceMessage *SuppressionSourceMessageData `json:"source_message,omitempty"`
	CreatedAt     string                        `json:"created_at"`
	UpdatedAt     string                        `json:"updated_at"`
}

type SuppressionReason string

const (
	SuppressionReasonSpamComplaint SuppressionReason = "spam_complaint"
	SuppressionReasonHardBounce    SuppressionReason = "hard_bounce"
	SuppressionReasonUnsubscribe   SuppressionReason = "unsubscribe"
	SuppressionReasonManual        SuppressionReason = "manual"
)

type SuppressionScope string

const (
	SuppressionScopeGlobal  SuppressionScope = "global"
	SuppressionScopeTeam    SuppressionScope = "team"
	SuppressionScopeProject SuppressionScope = "project"
	SuppressionScopeRoute   SuppressionScope = "route"
)

type SuppressionSourceMessageData struct {
	ID        string  `json:"id"`
	Available bool    `json:"available"`
	Subject   *string `json:"subject"`
	CreatedAt *string `json:"created_at"`
}

type SuppressionType string

const (
	SuppressionTypeEmail     SuppressionType = "email"
	SuppressionTypeDomain    SuppressionType = "domain"
	SuppressionTypeExtension SuppressionType = "extension"
)

type TeamAddonData struct {
	Type      *string `json:"type"`
	ExpiresAt *string `json:"expires_at"`
}

type TeamData struct {
	ID             string          `json:"id"`
	Name           string          `json:"name"`
	Type           TeamType        `json:"type"`
	Plan           Plan            `json:"plan"`
	IncludedVolume int             `json:"included_volume"`
	Tier           int             `json:"tier"`
	VerifiedAt     *string         `json:"verified_at"`
	Features       []string        `json:"features,omitempty"`
	Addons         []TeamAddonData `json:"addons,omitempty"`
	CreatedAt      string          `json:"created_at"`
	DomainsCount   int             `json:"domains_count,omitempty"`
	ProjectsCount  int             `json:"projects_count,omitempty"`
	MembersCount   int             `json:"members_count,omitempty"`
}

type TeamMemberData struct {
	ID            string                      `json:"id"`
	Name          string                      `json:"name"`
	Email         string                      `json:"email"`
	Role          map[string]interface{}      `json:"role"`
	ProjectAccess TeamMemberProjectAccessData `json:"project_access"`
	JoinedAt      *string                     `json:"joined_at"`
}

type TeamMemberProjectAccessData struct {
	Scope    ProjectAccessScope       `json:"scope"`
	Projects []map[string]interface{} `json:"projects"`
}

type TeamRoleData struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	SystemKey   *BuiltInTeamRole `json:"system_key"`
	Permissions []RbacPermission `json:"permissions"`
	Assignable  bool             `json:"assignable"`
}

type TeamType string

const (
	TeamTypePersonal TeamType = "personal"
	TeamTypeBusiness TeamType = "business"
)

type TeamUsageDetailData struct {
	CurrentPeriod   TeamUsagePeriodData   `json:"current_period"`
	HistoricalUsage []TeamUsagePeriodData `json:"historical_usage"`
}

type TeamUsagePeriodData struct {
	Usage             int     `json:"usage"`
	LastIncrementedAt *string `json:"last_incremented_at"`
	PeriodStart       string  `json:"period_start"`
	PeriodEnd         string  `json:"period_end"`
}

type UpdateDomainProjectsData struct {
	ProjectIDs []string `json:"project_ids"`
}

type UpdateProjectData struct {
	Name               *string `json:"name,omitempty"`
	SMTPEnabled        *bool   `json:"smtp_enabled,omitempty"`
	RedactEmailContent *bool   `json:"redact_email_content,omitempty"`
	DefaultRouteID     *string `json:"default_route_id,omitempty"`
}

type UpdateRouteData struct {
	Name            *string                         `json:"name,omitempty"`
	Settings        *UpdateRouteSettingsData        `json:"settings,omitempty"`
	InboundSettings *UpdateRouteInboundSettingsData `json:"inbound_settings,omitempty"`
}

type UpdateRouteInboundSettingsData struct {
	InboundDomain        *string             `json:"inbound_domain,omitempty"`
	InboundSpamThreshold *float64            `json:"inbound_spam_threshold,omitempty"`
	AttachmentDelivery   *AttachmentDelivery `json:"attachment_delivery,omitempty"`
}

type UpdateRouteSettingsData struct {
	TrackOpens                   *bool      `json:"track_opens,omitempty"`
	TrackClicks                  *bool      `json:"track_clicks,omitempty"`
	GeneratePlaintextFallback    *bool      `json:"generate_plaintext_fallback,omitempty"`
	SuppressAutoResponders       *bool      `json:"suppress_auto_responders,omitempty"`
	SuppressDisposableRecipients *bool      `json:"suppress_disposable_recipients,omitempty"`
	Tls                          *TlsPolicy `json:"tls,omitempty"`
	DisableHostedUnsubscribe     *bool      `json:"disable_hosted_unsubscribe,omitempty"`
	RedactEmailContent           *bool      `json:"redact_email_content,omitempty"`
}

type UpdateTeamData struct {
	Name *string `json:"name,omitempty"`
}

type UpdateTeamMemberAssignmentData struct {
	RoleID        string                 `json:"role_id"`
	ProjectAccess map[string]interface{} `json:"project_access"`
}

type UpdateWebhookData struct {
	Name                 string            `json:"name,omitempty"`
	URL                  string            `json:"url,omitempty"`
	Events               []APIWebhookEvent `json:"events,omitempty"`
	Enabled              *bool             `json:"enabled,omitempty"`
	IncludeMachineEvents *bool             `json:"include_machine_events,omitempty"`
}

type WebhookData struct {
	ID                   string   `json:"id"`
	RouteID              string   `json:"route_id"`
	Name                 string   `json:"name"`
	URL                  string   `json:"url"`
	Events               []string `json:"events"`
	Enabled              bool     `json:"enabled"`
	IncludeMachineEvents bool     `json:"include_machine_events"`
	Secret               string   `json:"secret,omitempty"`
	LastCalledAt         *string  `json:"last_called_at"`
	CreatedAt            string   `json:"created_at"`
	UpdatedAt            string   `json:"updated_at"`
}

type WebhookDeliveryData struct {
	ID              string                `json:"id"`
	WebhookID       string                `json:"webhook_id"`
	EventType       APIWebhookEvent       `json:"event_type"`
	Status          WebhookDeliveryStatus `json:"status"`
	AttemptNumber   int                   `json:"attempt_number"`
	HttpStatusCode  *int                  `json:"http_status_code"`
	DurationMs      *int                  `json:"duration_ms"`
	Payload         []string              `json:"payload"`
	ResponseBody    *string               `json:"response_body"`
	ResponseHeaders []string              `json:"response_headers"`
	ErrorMessage    *string               `json:"error_message"`
	DeliveredAt     *string               `json:"delivered_at"`
	Timestamp       string                `json:"timestamp"`
}

type WebhookDeliveryListData struct {
	ID             string                `json:"id"`
	WebhookID      string                `json:"webhook_id"`
	EventType      APIWebhookEvent       `json:"event_type"`
	Status         WebhookDeliveryStatus `json:"status"`
	AttemptNumber  int                   `json:"attempt_number"`
	HttpStatusCode *int                  `json:"http_status_code"`
	DurationMs     *int                  `json:"duration_ms"`
	DeliveredAt    *string               `json:"delivered_at"`
	CreatedAt      string                `json:"created_at"`
}

type WebhookDeliveryStatus string

const (
	WebhookDeliveryStatusPending     WebhookDeliveryStatus = "pending"
	WebhookDeliveryStatusSuccess     WebhookDeliveryStatus = "success"
	WebhookDeliveryStatusFailed      WebhookDeliveryStatus = "failed"
	WebhookDeliveryStatusClientError WebhookDeliveryStatus = "client_error"
	WebhookDeliveryStatusServerError WebhookDeliveryStatus = "server_error"
	WebhookDeliveryStatusTimeout     WebhookDeliveryStatus = "timeout"
)

type APIWebhookEvent string

const (
	APIWebhookEventMessageCreated        APIWebhookEvent = "message.created"
	APIWebhookEventMessageSent           APIWebhookEvent = "message.sent"
	APIWebhookEventMessageDelivered      APIWebhookEvent = "message.delivered"
	APIWebhookEventMessageAutoReplied    APIWebhookEvent = "message.auto_replied"
	APIWebhookEventMessageHardBounced    APIWebhookEvent = "message.hard_bounced"
	APIWebhookEventMessageSoftBounced    APIWebhookEvent = "message.soft_bounced"
	APIWebhookEventMessageSpamComplaint  APIWebhookEvent = "message.spam_complaint"
	APIWebhookEventMessageFailed         APIWebhookEvent = "message.failed"
	APIWebhookEventMessageSuppressed     APIWebhookEvent = "message.suppressed"
	APIWebhookEventMessageUnsubscribed   APIWebhookEvent = "message.unsubscribed"
	APIWebhookEventMessageOpened         APIWebhookEvent = "message.opened"
	APIWebhookEventMessageClicked        APIWebhookEvent = "message.clicked"
	APIWebhookEventMessageInbound        APIWebhookEvent = "message.inbound"
	APIWebhookEventMessagePolicyRejected APIWebhookEvent = "message.policy_rejected"
	APIWebhookEventSuppressionAdded      APIWebhookEvent = "suppression.added"
	APIWebhookEventSuppressionRemoved    APIWebhookEvent = "suppression.removed"
	APIWebhookEventWebhookTest           APIWebhookEvent = "webhook.test"
)

type WebhookListData struct {
	ID           string            `json:"id"`
	RouteID      string            `json:"route_id"`
	Name         string            `json:"name"`
	URL          string            `json:"url"`
	Events       []APIWebhookEvent `json:"events"`
	Enabled      bool              `json:"enabled"`
	LastCalledAt *string           `json:"last_called_at"`
	CreatedAt    string            `json:"created_at"`
	UpdatedAt    string            `json:"updated_at"`
}

type SendMailResponse struct {
	MessageID   *string       `json:"message_id"`
	Status      MessageStatus `json:"status"`
	ScheduledAt *string       `json:"scheduled_at,omitempty"`
}

type SendBatchMailResponse []SendMailResponse
type EmailPayload = SendMailRequest
type SendEmailResponse = SendMailResponse
type SendBatchEmailResponse = SendBatchMailResponse

type PingResponse int

type DomainIndexResponse struct {
	Data        []DomainListData `json:"data"`
	Path        *string          `json:"path"`
	PerPage     int              `json:"per_page"`
	NextCursor  *string          `json:"next_cursor"`
	NextPageURL *string          `json:"next_page_url"`
	PrevCursor  *string          `json:"prev_cursor"`
	PrevPageURL *string          `json:"prev_page_url"`
}

type DomainStoreRequest StoreDomainData

type DomainStoreResponse DomainData

type DomainShowResponse DomainData

type DomainDestroyResponse struct {
	Message string `json:"message"`
}

type DomainVerifyDNSRecordsResponse struct {
	Message                  string                   `json:"message"`
	RecommendedFailedRecords []map[string]interface{} `json:"recommended_failed_records"`
}

type DomainVerifySpecificDNSRecordResponse struct {
	Message string `json:"message"`
}

type DomainUpdateProjectsRequest UpdateDomainProjectsData

type DomainUpdateProjectsResponse struct {
	Data    DomainData `json:"data"`
	Message string     `json:"message"`
}

type BlockedFileTypesResponse struct {
	Extensions []string `json:"extensions"`
	MimeTypes  []string `json:"mime_types"`
}

type MessageIndexResponse struct {
	Data  []MessageListData      `json:"data"`
	Links []string               `json:"links"`
	Meta  map[string]interface{} `json:"meta"`
}

type MessageShowResponse MessageData

type MessageEventsResponse struct {
	Data  []MessageEventData     `json:"data"`
	Links []string               `json:"links"`
	Meta  map[string]interface{} `json:"meta"`
}

type ProcessInboundMessageResponse struct {
	Data map[string]interface{} `json:"data"`
}

type ProjectIndexResponse struct {
	Data        []ProjectListData `json:"data"`
	Path        *string           `json:"path"`
	PerPage     int               `json:"per_page"`
	NextCursor  *string           `json:"next_cursor"`
	NextPageURL *string           `json:"next_page_url"`
	PrevCursor  *string           `json:"prev_cursor"`
	PrevPageURL *string           `json:"prev_page_url"`
}

type ProjectStoreRequest StoreProjectData

type ProjectStoreResponse struct {
	Data     ProjectData `json:"data"`
	Message  string      `json:"message"`
	APIToken string      `json:"api_token"`
}

type ProjectShowResponse ProjectData

type ProjectUpdateRequest UpdateProjectData

type ProjectUpdateResponse struct {
	Data    ProjectData `json:"data"`
	Message string      `json:"message"`
}

type ProjectDestroyResponse struct {
	Message string `json:"message"`
}

type ProjectRotateTokenResponse struct {
	Data     ProjectData `json:"data"`
	NewToken string      `json:"new_token"`
	Message  string      `json:"message"`
}

type RouteIndexResponse struct {
	Data        []RouteListData `json:"data"`
	Path        *string         `json:"path"`
	PerPage     int             `json:"per_page"`
	NextCursor  *string         `json:"next_cursor"`
	NextPageURL *string         `json:"next_page_url"`
	PrevCursor  *string         `json:"prev_cursor"`
	PrevPageURL *string         `json:"prev_page_url"`
}

type RouteStoreRequest StoreRouteData

type RouteStoreResponse struct {
	Data    RouteData `json:"data"`
	Message string    `json:"message"`
}

type RouteShowResponse RouteData

type RouteUpdateRequest UpdateRouteData

type RouteUpdateResponse struct {
	Data    RouteData `json:"data"`
	Message string    `json:"message"`
}

type RouteDestroyResponse struct {
	Message string `json:"message"`
}

type RouteVerifyInboundDomainResponse struct {
	Data map[string]interface{} `json:"data"`
}

type StatsIndexResponse StatsData

type SuppressionIndexResponse struct {
	Data        []SuppressedRecipientData `json:"data"`
	Path        *string                   `json:"path"`
	PerPage     int                       `json:"per_page"`
	NextCursor  *string                   `json:"next_cursor"`
	NextPageURL *string                   `json:"next_page_url"`
	PrevCursor  *string                   `json:"prev_cursor"`
	PrevPageURL *string                   `json:"prev_page_url"`
}

type SuppressionStoreRequest StoreSuppressionData

type SuppressionStoreResponse struct {
	Message interface{}            `json:"message"`
	Data    map[string]interface{} `json:"data"`
}

type SuppressionDestroyResponse struct {
	Success    bool    `json:"success"`
	Status     string  `json:"status"`
	Message    string  `json:"message"`
	Confidence float64 `json:"confidence,omitempty"`
}

type TeamShowResponse TeamData

type TeamUpdateRequest UpdateTeamData

type TeamUpdateResponse struct {
	Data    TeamData `json:"data"`
	Message string   `json:"message"`
}

type TeamUsageResponse TeamUsageDetailData

type TeamRolesResponse struct {
	Data []TeamRoleData `json:"data"`
}

type TeamMembersResponse struct {
	Data        []TeamMemberData `json:"data"`
	Path        *string          `json:"path"`
	PerPage     int              `json:"per_page"`
	NextCursor  *string          `json:"next_cursor"`
	NextPageURL *string          `json:"next_page_url"`
	PrevCursor  *string          `json:"prev_cursor"`
	PrevPageURL *string          `json:"prev_page_url"`
}

type TeamMembersShowResponse TeamMemberData

type TeamMembersAssignmentUpdateRequest UpdateTeamMemberAssignmentData

type TeamMembersAssignmentUpdateResponse TeamMemberData

type WebhookIndexResponse struct {
	Data        []WebhookListData `json:"data"`
	Path        *string           `json:"path"`
	PerPage     int               `json:"per_page"`
	NextCursor  *string           `json:"next_cursor"`
	NextPageURL *string           `json:"next_page_url"`
	PrevCursor  *string           `json:"prev_cursor"`
	PrevPageURL *string           `json:"prev_page_url"`
}

type WebhookStoreRequest StoreWebhookData

type WebhookStoreResponse struct {
	Data    WebhookData `json:"data"`
	Message string      `json:"message"`
}

type WebhookShowResponse WebhookData

type WebhookUpdateRequest UpdateWebhookData

type WebhookUpdateResponse struct {
	Data    WebhookData `json:"data"`
	Message string      `json:"message"`
}

type WebhookDestroyResponse struct {
	Message string `json:"message"`
}

type WebhookTestResponse struct {
	Message    string `json:"message"`
	DeliveryID string `json:"delivery_id"`
}

type WebhookRegenerateSecretResponse struct {
	Data    WebhookData `json:"data"`
	Message string      `json:"message"`
}

type WebhookDeliveriesResponse struct {
	Data        []WebhookDeliveryListData `json:"data"`
	Path        *string                   `json:"path"`
	PerPage     int                       `json:"per_page"`
	NextCursor  *string                   `json:"next_cursor"`
	NextPageURL *string                   `json:"next_page_url"`
	PrevCursor  *string                   `json:"prev_cursor"`
	PrevPageURL *string                   `json:"prev_page_url"`
}

type WebhookShowDeliveryResponse WebhookDeliveryData
