// Code generated by lettermint/sdk-generator. DO NOT EDIT.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

package lettermint

// authSurface says which API token an operation accepts.
type authSurface string

const (
	authSending authSurface = "sending"
	authTeam    authSurface = "team"
	authEither  authSurface = "either"
)

// operationKey identifies an operation as "<METHOD> <path>".
type operationKey string

// operation describes one operation of the Sending or Team API. Type names
// are Go type names; a response Type is a type name, "text" or "empty".
type operation struct {
	OperationID string
	Method      string
	Path        string
	Auth        authSurface
	Surfaces    []string
	PathParams  []string
	Query       string
	Headers     []string
	Request     *operationRequest
	Response    operationResponse
	Errors      map[int][]string
	Pagination  *operationPagination
	Deprecated  bool
}

type operationRequest struct {
	Type        string
	ContentType string
	Required    bool
}

type operationResponse struct {
	Status      []int
	ContentType string
	Type        string
}

// operationPagination describes a cursor-paginated list: the item type and
// the query parameters that carry the cursor and the page size.
type operationPagination struct {
	Items       string
	CursorParam string
	SizeParam   string
}

// Every operation, as a constant named after its operationId.
const (
	opCancelScheduledMessage     operationKey = "POST /messages/{messageId}/cancel"
	opCreateDomain               operationKey = "POST /domains"
	opCreateProject              operationKey = "POST /projects"
	opCreateRoute                operationKey = "POST /projects/{projectId}/routes"
	opCreateSuppressions         operationKey = "POST /suppressions"
	opCreateWebhook              operationKey = "POST /webhooks"
	opDeleteDomain               operationKey = "DELETE /domains/{domainId}"
	opDeleteProject              operationKey = "DELETE /projects/{projectId}"
	opDeleteReportForwarding     operationKey = "DELETE /projects/{projectId}/report-forwarding"
	opDeleteRoute                operationKey = "DELETE /routes/{routeId}"
	opDeleteSuppression          operationKey = "DELETE /suppressions/{suppressionId}"
	opDeleteWebhook              operationKey = "DELETE /webhooks/{webhookId}"
	opGetDomain                  operationKey = "GET /domains/{domainId}"
	opGetMessage                 operationKey = "GET /messages/{messageId}"
	opGetMessageHtml             operationKey = "GET /messages/{messageId}/html"
	opGetMessageSource           operationKey = "GET /messages/{messageId}/source"
	opGetMessageText             operationKey = "GET /messages/{messageId}/text"
	opGetProject                 operationKey = "GET /projects/{projectId}"
	opGetReportForwarding        operationKey = "GET /projects/{projectId}/report-forwarding"
	opGetRoute                   operationKey = "GET /routes/{routeId}"
	opGetStats                   operationKey = "GET /stats"
	opGetTeam                    operationKey = "GET /team"
	opGetTeamMember              operationKey = "GET /team/members/{userId}"
	opGetTeamUsage               operationKey = "GET /team/usage"
	opGetWebhook                 operationKey = "GET /webhooks/{webhookId}"
	opGetWebhookDelivery         operationKey = "GET /webhooks/{webhookId}/deliveries/{deliveryId}"
	opListBlockedFileTypes       operationKey = "GET /blocked-file-types"
	opListDomains                operationKey = "GET /domains"
	opListMessageEvents          operationKey = "GET /messages/{messageId}/events"
	opListMessages               operationKey = "GET /messages"
	opListProjects               operationKey = "GET /projects"
	opListRoutes                 operationKey = "GET /projects/{projectId}/routes"
	opListSuppressions           operationKey = "GET /suppressions"
	opListTeamMembers            operationKey = "GET /team/members"
	opListTeamRoles              operationKey = "GET /team/roles"
	opListWebhookDeliveries      operationKey = "GET /webhooks/{webhookId}/deliveries"
	opListWebhooks               operationKey = "GET /webhooks"
	opPing                       operationKey = "GET /ping"
	opProcessInboundMessage      operationKey = "POST /messages/{messageId}/process"
	opQueryAnalytics             operationKey = "POST /analytics"
	opRegenerateWebhookSecret    operationKey = "POST /webhooks/{webhookId}/regenerate-secret"
	opRescheduleMessage          operationKey = "PATCH /messages/{messageId}"
	opResendReportForwardingCode operationKey = "POST /projects/{projectId}/report-forwarding/resend-code"
	opRotateProjectToken         operationKey = "POST /projects/{projectId}/rotate-token"
	opSendBatchMail              operationKey = "POST /send/batch"
	opSendMail                   operationKey = "POST /send"
	opTestWebhook                operationKey = "POST /webhooks/{webhookId}/test"
	opUpdateDomainProjects       operationKey = "PUT /domains/{domainId}/projects"
	opUpdateProject              operationKey = "PUT /projects/{projectId}"
	opUpdateReportForwarding     operationKey = "PUT /projects/{projectId}/report-forwarding"
	opUpdateRoute                operationKey = "PUT /routes/{routeId}"
	opUpdateTeam                 operationKey = "PUT /team"
	opUpdateTeamMemberAssignment operationKey = "PUT /team/members/{userId}/assignment"
	opUpdateWebhook              operationKey = "PUT /webhooks/{webhookId}"
	opVerifyDomainDnsRecord      operationKey = "POST /domains/{domainId}/dns-records/{recordId}/verify"
	opVerifyDomainDnsRecords     operationKey = "POST /domains/{domainId}/dns-records/verify"
	opVerifyReportForwarding     operationKey = "POST /projects/{projectId}/report-forwarding/verify"
	opVerifyRouteInboundDomain   operationKey = "POST /routes/{routeId}/verify-inbound-domain"
)

// operations describes every operation of the Sending and Team APIs.
var operations = map[operationKey]operation{
	// Cancel a scheduled message
	opCancelScheduledMessage: {
		OperationID: "cancelScheduledMessage",
		Method:      "POST",
		Path:        "/messages/{messageId}/cancel",
		Auth:        authEither,
		Surfaces:    []string{"team"},
		PathParams:  []string{"messageId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "ScheduledMessage"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			409: []string{"ApiErrorBody", "ErrorMessage"},
			422: []string{"ErrorMessage"},
		},
	},
	// Create a new domain
	opCreateDomain: {
		OperationID: "createDomain",
		Method:      "POST",
		Path:        "/domains",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  nil,
		Query:       "",
		Headers:     nil,
		Request:     &operationRequest{Type: "StoreDomainData", ContentType: "application/json", Required: true},
		Response:    operationResponse{Status: []int{201}, ContentType: "application/json", Type: "DomainData"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			422: []string{"ValidationException"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
			500: []string{"ApiErrorBody"},
		},
	},
	// Create a new project
	opCreateProject: {
		OperationID: "createProject",
		Method:      "POST",
		Path:        "/projects",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  nil,
		Query:       "",
		Headers:     nil,
		Request:     &operationRequest{Type: "StoreProjectData", ContentType: "application/json", Required: true},
		Response:    operationResponse{Status: []int{201}, ContentType: "application/json", Type: "ProjectCreatedData"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			422: []string{"ValidationException"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Create a new route
	opCreateRoute: {
		OperationID: "createRoute",
		Method:      "POST",
		Path:        "/projects/{projectId}/routes",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"projectId"},
		Query:       "",
		Headers:     nil,
		Request:     &operationRequest{Type: "StoreRouteData", ContentType: "application/json", Required: true},
		Response:    operationResponse{Status: []int{201}, ContentType: "application/json", Type: "RouteMutationResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			422: []string{"ApiErrorBody", "ValidationErrorBody"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Add email(s) to suppression list
	opCreateSuppressions: {
		OperationID: "createSuppressions",
		Method:      "POST",
		Path:        "/suppressions",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  nil,
		Query:       "",
		Headers:     nil,
		Request:     &operationRequest{Type: "StoreSuppressionData", ContentType: "application/json", Required: true},
		Response:    operationResponse{Status: []int{201}, ContentType: "application/json", Type: "SuppressionStoreResponse"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			404: []string{"ModelNotFoundException"},
			422: []string{"ValidationException"},
			429: []string{"TooManyRequests"},
		},
	},
	// Create a new webhook
	opCreateWebhook: {
		OperationID: "createWebhook",
		Method:      "POST",
		Path:        "/webhooks",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  nil,
		Query:       "",
		Headers:     nil,
		Request:     &operationRequest{Type: "StoreWebhookData", ContentType: "application/json", Required: true},
		Response:    operationResponse{Status: []int{201}, ContentType: "application/json", Type: "WebhookSecretResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			422: []string{"ValidationException"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Delete a domain
	opDeleteDomain: {
		OperationID: "deleteDomain",
		Method:      "DELETE",
		Path:        "/domains/{domainId}",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"domainId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "MessageResponse"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			429: []string{"TooManyRequests"},
		},
	},
	// Delete a project
	opDeleteProject: {
		OperationID: "deleteProject",
		Method:      "DELETE",
		Path:        "/projects/{projectId}",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"projectId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "MessageResponse"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			429: []string{"TooManyRequests"},
		},
	},
	// Disable report forwarding
	opDeleteReportForwarding: {
		OperationID: "deleteReportForwarding",
		Method:      "DELETE",
		Path:        "/projects/{projectId}/report-forwarding",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"projectId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{204}, ContentType: "", Type: "empty"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ModelNotFoundException"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Delete a route
	opDeleteRoute: {
		OperationID: "deleteRoute",
		Method:      "DELETE",
		Path:        "/routes/{routeId}",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"routeId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "MessageResponse"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			422: []string{"ApiErrorBody"},
			429: []string{"TooManyRequests"},
		},
	},
	// Remove email from suppression list
	opDeleteSuppression: {
		OperationID: "deleteSuppression",
		Method:      "DELETE",
		Path:        "/suppressions/{suppressionId}",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"suppressionId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200, 202}, ContentType: "application/json", Type: "DeleteSuppressionResponse"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			404: []string{"ModelNotFoundException"},
			429: []string{"TooManyRequests"},
		},
	},
	// Delete a webhook
	opDeleteWebhook: {
		OperationID: "deleteWebhook",
		Method:      "DELETE",
		Path:        "/webhooks/{webhookId}",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"webhookId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "MessageResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Get domain details
	opGetDomain: {
		OperationID: "getDomain",
		Method:      "GET",
		Path:        "/domains/{domainId}",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"domainId"},
		Query:       "GetDomainQuery",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "DomainData"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Get message details
	opGetMessage: {
		OperationID: "getMessage",
		Method:      "GET",
		Path:        "/messages/{messageId}",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"messageId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "MessageData"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Get message HTML content
	opGetMessageHtml: {
		OperationID: "getMessageHtml",
		Method:      "GET",
		Path:        "/messages/{messageId}/html",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"messageId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "text/html; charset=UTF-8", Type: "text"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Get message source
	opGetMessageSource: {
		OperationID: "getMessageSource",
		Method:      "GET",
		Path:        "/messages/{messageId}/source",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"messageId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "message/rfc822", Type: "text"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ErrorMessage", "ApiErrorBody"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			410: []string{"ErrorMessage"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Get message plain text content
	opGetMessageText: {
		OperationID: "getMessageText",
		Method:      "GET",
		Path:        "/messages/{messageId}/text",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"messageId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "text/plain; charset=UTF-8", Type: "text"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Get project details
	opGetProject: {
		OperationID: "getProject",
		Method:      "GET",
		Path:        "/projects/{projectId}",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"projectId"},
		Query:       "GetProjectQuery",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "ProjectData"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Get report forwarding settings
	opGetReportForwarding: {
		OperationID: "getReportForwarding",
		Method:      "GET",
		Path:        "/projects/{projectId}/report-forwarding",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"projectId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "GetReportForwardingResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ModelNotFoundException"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Get route details
	opGetRoute: {
		OperationID: "getRoute",
		Method:      "GET",
		Path:        "/routes/{routeId}",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"routeId"},
		Query:       "GetRouteQuery",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "RouteData"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Get message statistics
	opGetStats: {
		OperationID: "getStats",
		Method:      "GET",
		Path:        "/stats",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  nil,
		Query:       "GetStatsQuery",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "StatsData"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			404: []string{"ModelNotFoundException"},
			422: []string{"ValidationException"},
			429: []string{"TooManyRequests"},
		},
	},
	// Get team details
	opGetTeam: {
		OperationID: "getTeam",
		Method:      "GET",
		Path:        "/team",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  nil,
		Query:       "GetTeamQuery",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "TeamData"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			429: []string{"TooManyRequests"},
		},
	},
	// Get a team member
	opGetTeamMember: {
		OperationID: "getTeamMember",
		Method:      "GET",
		Path:        "/team/members/{userId}",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"userId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "TeamMemberData"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			409: []string{"RbacConflictException"},
			429: []string{"TooManyRequests"},
		},
	},
	// Get team usage statistics
	opGetTeamUsage: {
		OperationID: "getTeamUsage",
		Method:      "GET",
		Path:        "/team/usage",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  nil,
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "TeamUsageDetailData"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			429: []string{"TooManyRequests"},
		},
	},
	// Get webhook details
	opGetWebhook: {
		OperationID: "getWebhook",
		Method:      "GET",
		Path:        "/webhooks/{webhookId}",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"webhookId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "WebhookData"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ApiErrorBody"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Get a specific webhook delivery
	opGetWebhookDelivery: {
		OperationID: "getWebhookDelivery",
		Method:      "GET",
		Path:        "/webhooks/{webhookId}/deliveries/{deliveryId}",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"webhookId", "deliveryId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "WebhookDeliveryData"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			404: []string{"ApiErrorBody", "ErrorMessage"},
			429: []string{"TooManyRequests"},
		},
	},
	// List blocked file types
	opListBlockedFileTypes: {
		OperationID: "listBlockedFileTypes",
		Method:      "GET",
		Path:        "/blocked-file-types",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  nil,
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "BlockedFileTypes"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			429: []string{"TooManyRequests"},
		},
	},
	// List all domains for the team
	opListDomains: {
		OperationID: "listDomains",
		Method:      "GET",
		Path:        "/domains",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  nil,
		Query:       "ListDomainsQuery",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "ListDomainsResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
		Pagination: &operationPagination{Items: "DomainListData", CursorParam: "page[cursor]", SizeParam: "page[size]"},
	},
	// Get message events
	opListMessageEvents: {
		OperationID: "listMessageEvents",
		Method:      "GET",
		Path:        "/messages/{messageId}/events",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"messageId"},
		Query:       "ListMessageEventsQuery",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "ListMessageEventsResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
		Pagination: &operationPagination{Items: "MessageEventData", CursorParam: "page[cursor]", SizeParam: "page[size]"},
	},
	// List messages for the team
	opListMessages: {
		OperationID: "listMessages",
		Method:      "GET",
		Path:        "/messages",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  nil,
		Query:       "ListMessagesQuery",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "ListMessagesResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			422: []string{"ValidationException"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
		Pagination: &operationPagination{Items: "MessageListData", CursorParam: "page[cursor]", SizeParam: "page[size]"},
	},
	// List all projects for the team
	opListProjects: {
		OperationID: "listProjects",
		Method:      "GET",
		Path:        "/projects",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  nil,
		Query:       "ListProjectsQuery",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "ListProjectsResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
		Pagination: &operationPagination{Items: "ProjectListData", CursorParam: "page[cursor]", SizeParam: "page[size]"},
	},
	// List routes for a project
	opListRoutes: {
		OperationID: "listRoutes",
		Method:      "GET",
		Path:        "/projects/{projectId}/routes",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"projectId"},
		Query:       "ListRoutesQuery",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "ListRoutesResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
		Pagination: &operationPagination{Items: "RouteListData", CursorParam: "page[cursor]", SizeParam: "page[size]"},
	},
	// List all suppressions for the team
	opListSuppressions: {
		OperationID: "listSuppressions",
		Method:      "GET",
		Path:        "/suppressions",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  nil,
		Query:       "ListSuppressionsQuery",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "ListSuppressionsResponse"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			422: []string{"ValidationException"},
			429: []string{"TooManyRequests"},
		},
		Pagination: &operationPagination{Items: "SuppressedRecipientData", CursorParam: "page[cursor]", SizeParam: "page[size]"},
	},
	// Get team members
	opListTeamMembers: {
		OperationID: "listTeamMembers",
		Method:      "GET",
		Path:        "/team/members",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  nil,
		Query:       "ListTeamMembersQuery",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "ListTeamMembersResponse"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			409: []string{"RbacConflictException"},
			429: []string{"TooManyRequests"},
		},
		Pagination: &operationPagination{Items: "TeamMemberData", CursorParam: "page[cursor]", SizeParam: "page[size]"},
	},
	// Get reusable team roles
	opListTeamRoles: {
		OperationID: "listTeamRoles",
		Method:      "GET",
		Path:        "/team/roles",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  nil,
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "TeamRoleListResponse"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			429: []string{"TooManyRequests"},
		},
	},
	// Get webhook deliveries
	opListWebhookDeliveries: {
		OperationID: "listWebhookDeliveries",
		Method:      "GET",
		Path:        "/webhooks/{webhookId}/deliveries",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"webhookId"},
		Query:       "ListWebhookDeliveriesQuery",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "ListWebhookDeliveriesResponse"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			429: []string{"TooManyRequests"},
		},
		Pagination: &operationPagination{Items: "WebhookDeliveryListData", CursorParam: "cursor", SizeParam: ""},
	},
	// List all webhooks for the team
	opListWebhooks: {
		OperationID: "listWebhooks",
		Method:      "GET",
		Path:        "/webhooks",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  nil,
		Query:       "ListWebhooksQuery",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "ListWebhooksResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
		Pagination: &operationPagination{Items: "WebhookListData", CursorParam: "cursor", SizeParam: "page[size]"},
	},
	// Ping the API
	opPing: {
		OperationID: "ping",
		Method:      "GET",
		Path:        "/ping",
		Auth:        authEither,
		Surfaces:    []string{"sending", "team"},
		PathParams:  nil,
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "text/html; charset=UTF-8", Type: "text"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody", "ErrorMessage"},
			429: []string{"TooManyRequests"},
		},
	},
	// Process one quarantined inbound message
	opProcessInboundMessage: {
		OperationID: "processInboundMessage",
		Method:      "POST",
		Path:        "/messages/{messageId}/process",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"messageId"},
		Query:       "",
		Headers:     []string{"Idempotency-Key"},
		Response:    operationResponse{Status: []int{202}, ContentType: "application/json", Type: "ProcessInboundMessageResponse"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			409: []string{"ProcessInboundMessageConflict", "ErrorMessage"},
			422: []string{"ErrorMessage"},
			429: []string{"TooManyRequests"},
		},
	},
	// Query email analytics
	opQueryAnalytics: {
		OperationID: "queryAnalytics",
		Method:      "POST",
		Path:        "/analytics",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  nil,
		Query:       "",
		Headers:     nil,
		Request:     &operationRequest{Type: "AnalyticsQuery", ContentType: "application/json", Required: true},
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "AnalyticsResponse"},
		Errors: map[int][]string{
			400: []string{"ErrorMessage"},
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			415: []string{"ErrorMessage"},
			422: []string{"ErrorMessage"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Regenerate webhook secret
	opRegenerateWebhookSecret: {
		OperationID: "regenerateWebhookSecret",
		Method:      "POST",
		Path:        "/webhooks/{webhookId}/regenerate-secret",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"webhookId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "WebhookSecretResponse"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			429: []string{"TooManyRequests"},
		},
	},
	// Reschedule a message
	opRescheduleMessage: {
		OperationID: "rescheduleMessage",
		Method:      "PATCH",
		Path:        "/messages/{messageId}",
		Auth:        authEither,
		Surfaces:    []string{"team"},
		PathParams:  []string{"messageId"},
		Query:       "",
		Headers:     nil,
		Request:     &operationRequest{Type: "RescheduleMessageRequest", ContentType: "application/json", Required: true},
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "ScheduledMessage"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody", "ErrorMessage"},
			403: []string{"ApiErrorBody"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			409: []string{"ApiErrorBody", "ErrorMessage"},
			422: []string{"ApiErrorBody", "ValidationErrorBody", "ErrorMessage"},
		},
	},
	// Resend report forwarding verification code
	opResendReportForwardingCode: {
		OperationID: "resendReportForwardingCode",
		Method:      "POST",
		Path:        "/projects/{projectId}/report-forwarding/resend-code",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"projectId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "ResendReportForwardingCodeResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ModelNotFoundException"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Rotate Project API token (legacy)
	//
	// Deprecated: the API marks this as deprecated.
	opRotateProjectToken: {
		OperationID: "rotateProjectToken",
		Method:      "POST",
		Path:        "/projects/{projectId}/rotate-token",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"projectId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "RotateProjectTokenResponse"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			429: []string{"TooManyRequests"},
		},
		Deprecated: true,
	},
	// Send multiple emails in a batch
	opSendBatchMail: {
		OperationID: "sendBatchMail",
		Method:      "POST",
		Path:        "/send/batch",
		Auth:        authSending,
		Surfaces:    []string{"sending"},
		PathParams:  nil,
		Query:       "",
		Headers:     []string{"Idempotency-Key"},
		Request:     &operationRequest{Type: "SendBatchMailRequest", ContentType: "application/json", Required: true},
		Response:    operationResponse{Status: []int{202}, ContentType: "application/json", Type: "SendBatchMailResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage"},
			403: []string{"ApiErrorBody"},
			409: []string{"ErrorMessage"},
			422: []string{"ApiErrorBody", "ValidationErrorBody", "ErrorMessage"},
			429: []string{"ApiErrorBody"},
			500: []string{"ApiErrorBody"},
		},
	},
	// Send an email
	opSendMail: {
		OperationID: "sendMail",
		Method:      "POST",
		Path:        "/send",
		Auth:        authSending,
		Surfaces:    []string{"sending"},
		PathParams:  nil,
		Query:       "",
		Headers:     []string{"Idempotency-Key"},
		Request:     &operationRequest{Type: "SendMailRequest", ContentType: "application/json", Required: true},
		Response:    operationResponse{Status: []int{202}, ContentType: "application/json", Type: "SendMailResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			409: []string{"ErrorMessage"},
			422: []string{"ErrorMessage", "ApiErrorBody", "ValidationErrorBody"},
			429: []string{"ApiErrorBody"},
			500: []string{"ApiErrorBody"},
		},
	},
	// Test a webhook by sending a sample payload
	opTestWebhook: {
		OperationID: "testWebhook",
		Method:      "POST",
		Path:        "/webhooks/{webhookId}/test",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"webhookId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "TestWebhookResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Update projects associated with a domain
	opUpdateDomainProjects: {
		OperationID: "updateDomainProjects",
		Method:      "PUT",
		Path:        "/domains/{domainId}/projects",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"domainId"},
		Query:       "",
		Headers:     nil,
		Request:     &operationRequest{Type: "UpdateDomainProjectsData", ContentType: "application/json", Required: true},
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "DomainMutationResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			422: []string{"ApiErrorBody", "ValidationErrorBody"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Update project settings
	opUpdateProject: {
		OperationID: "updateProject",
		Method:      "PUT",
		Path:        "/projects/{projectId}",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"projectId"},
		Query:       "",
		Headers:     nil,
		Request:     &operationRequest{Type: "UpdateProjectData", ContentType: "application/json", Required: false},
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "ProjectMutationResponse"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			422: []string{"ValidationException"},
			429: []string{"TooManyRequests"},
		},
	},
	// Update report forwarding destination
	opUpdateReportForwarding: {
		OperationID: "updateReportForwarding",
		Method:      "PUT",
		Path:        "/projects/{projectId}/report-forwarding",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"projectId"},
		Query:       "",
		Headers:     nil,
		Request:     &operationRequest{Type: "ReportForwardingRequest", ContentType: "application/json", Required: true},
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "UpdateReportForwardingResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ModelNotFoundException"},
			422: []string{"ValidationException"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Update route settings
	opUpdateRoute: {
		OperationID: "updateRoute",
		Method:      "PUT",
		Path:        "/routes/{routeId}",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"routeId"},
		Query:       "",
		Headers:     nil,
		Request:     &operationRequest{Type: "UpdateRouteData", ContentType: "application/json", Required: false},
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "RouteMutationResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			422: []string{"ValidationException"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Update team settings
	opUpdateTeam: {
		OperationID: "updateTeam",
		Method:      "PUT",
		Path:        "/team",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  nil,
		Query:       "",
		Headers:     nil,
		Request:     &operationRequest{Type: "UpdateTeamData", ContentType: "application/json", Required: false},
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "TeamMutationResponse"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			422: []string{"ValidationException"},
			429: []string{"TooManyRequests"},
		},
	},
	// Replace a team member's assignment
	opUpdateTeamMemberAssignment: {
		OperationID: "updateTeamMemberAssignment",
		Method:      "PUT",
		Path:        "/team/members/{userId}/assignment",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"userId"},
		Query:       "",
		Headers:     nil,
		Request:     &operationRequest{Type: "UpdateTeamMemberAssignmentData", ContentType: "application/json", Required: true},
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "TeamMemberData"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			409: []string{"RbacConflictException"},
			422: []string{"ValidationException"},
			429: []string{"TooManyRequests"},
		},
	},
	// Update webhook settings
	opUpdateWebhook: {
		OperationID: "updateWebhook",
		Method:      "PUT",
		Path:        "/webhooks/{webhookId}",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"webhookId"},
		Query:       "",
		Headers:     nil,
		Request:     &operationRequest{Type: "UpdateWebhookData", ContentType: "application/json", Required: false},
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "WebhookMutationResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			422: []string{"ValidationException"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Verify a specific DNS record
	opVerifyDomainDnsRecord: {
		OperationID: "verifyDomainDnsRecord",
		Method:      "POST",
		Path:        "/domains/{domainId}/dns-records/{recordId}/verify",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"domainId", "recordId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "MessageResponse"},
		Errors: map[int][]string{
			401: []string{"ApiErrorBody"},
			403: []string{"ApiErrorBody"},
			404: []string{"ApiErrorBody", "ErrorMessage"},
			422: []string{"DnsRecordVerificationFailureResponse"},
			429: []string{"TooManyRequests"},
		},
	},
	// Verify all DNS records for a domain
	opVerifyDomainDnsRecords: {
		OperationID: "verifyDomainDnsRecords",
		Method:      "POST",
		Path:        "/domains/{domainId}/dns-records/verify",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"domainId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "DnsVerificationSuccessResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			422: []string{"DnsVerificationFailureResponse"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Verify report forwarding destination
	opVerifyReportForwarding: {
		OperationID: "verifyReportForwarding",
		Method:      "POST",
		Path:        "/projects/{projectId}/report-forwarding/verify",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"projectId"},
		Query:       "",
		Headers:     nil,
		Request:     &operationRequest{Type: "VerifyReportForwardingRequest", ContentType: "application/json", Required: true},
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "VerifyReportForwardingResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ModelNotFoundException"},
			422: []string{"ValidationException"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
	// Verify inbound domain for a route
	opVerifyRouteInboundDomain: {
		OperationID: "verifyRouteInboundDomain",
		Method:      "POST",
		Path:        "/routes/{routeId}/verify-inbound-domain",
		Auth:        authTeam,
		Surfaces:    []string{"team"},
		PathParams:  []string{"routeId"},
		Query:       "",
		Headers:     nil,
		Response:    operationResponse{Status: []int{200}, ContentType: "application/json", Type: "InboundDomainVerificationResponse"},
		Errors: map[int][]string{
			401: []string{"ErrorMessage", "ApiErrorBody"},
			403: []string{"ApiErrorBody", "ErrorMessage"},
			404: []string{"ErrorMessage", "ApiErrorBody"},
			422: []string{"InboundDomainVerificationResponse", "ApiErrorBody"},
			429: []string{"ErrorMessage", "ApiErrorBody"},
		},
	},
}
