package lettermint

import (
	"bufio"
	"encoding/json"
	"os"
	"regexp"
	"runtime/debug"
	"testing"
	"time"
)

func TestEncodeQuery(t *testing.T) {
	type inner struct {
		I string `query:"i"`
		K struct {
			L string `query:"l"`
		} `query:"k"`
	}
	type item struct {
		Name  string `query:"name"`
		Value string `query:"value"`
	}
	yes, no := true, false
	query := struct {
		A     int               `query:"a"`
		B     *bool             `query:"b"`
		C     *bool             `query:"c"`
		D     *string           `query:"d"`
		E     string            `query:"e"`
		F     []string          `query:"f"`
		G     []string          `query:"g"`
		H     inner             `query:"h"`
		N     time.Time         `query:"n"`
		Size  int               `query:"page[size]"`
		Items []item            `query:"items"`
		Ptrs  []*string         `query:"ptrs"`
		Skip  string            `query:"-"`
		JSON  string            `json:"json_name,omitempty"`
		Times []float64         `query:"floats"`
		Nest  *inner            `query:"nil"`
		Bools []bool            `query:"bools"`
		Map   map[string]string `query:"m"`
	}{
		A: 1, B: &yes, C: &no, F: []string{}, G: []string{"x", "y"},
		N: time.Date(2026, 1, 2, 3, 4, 5, 0, time.FixedZone("x", 3600)), Size: 5,
		Items: []item{{Name: "a", Value: "1"}, {Name: "b"}}, Ptrs: []*string{Ptr("p"), nil, Ptr("q")},
		Skip: "skipped", JSON: "j", Times: []float64{0.5, 2}, Bools: []bool{true, false},
		Map: map[string]string{"z": "1", "a": "2"},
	}
	query.H.I = "j"
	query.H.K.L = "m"
	pairs, err := encodeQuery(&query)
	if err != nil {
		t.Fatal(err)
	}
	got := formEncode(pairs)
	want := "a=1&b=1&c=0&g=x%2Cy&h%5Bi%5D=j&h%5Bk%5D%5Bl%5D=m&n=2026-01-02T02%3A04%3A05.000Z&page%5Bsize%5D=5&items%5B0%5D%5Bname%5D=a&items%5B0%5D%5Bvalue%5D=1&items%5B1%5D%5Bname%5D=b&ptrs=p%2Cq&json_name=j&floats=0.5%2C2&bools=1%2C0&m%5Ba%5D=2&m%5Bz%5D=1"
	if got != want {
		t.Fatalf("\n%s\n%s", got, want)
	}
	if pairs, _ := encodeQuery(nil); pairs != nil {
		t.Fatal(pairs)
	}
	var nilQuery *ListDomainsQuery
	if pairs, _ := encodeQuery(nilQuery); pairs != nil {
		t.Fatal(pairs)
	}
	if _, err := encodeQuery("not a struct"); err == nil {
		t.Fatal("a query must be a struct")
	}
}

func TestFormEscapeMatchesURLSearchParams(t *testing.T) {
	// new URLSearchParams({ filter: 'a&b=c #d*~é' }).toString()
	if got := formEscape("a&b=c #d*~é-._"); got != "a%26b%3Dc+%23d*%7E%C3%A9-._" {
		t.Fatal(got)
	}
}

func TestSetQueryParam(t *testing.T) {
	pairs := []queryPair{{"page[size]", "2"}, {"page[cursor]", "old"}, {"page[cursor]", "older"}}
	got := setQueryParam(pairs, "page[cursor]", "next")
	if len(got) != 2 || got[1] != (queryPair{"page[cursor]", "next"}) || pairs[1].value != "old" {
		t.Fatal(got, pairs)
	}
	if got := setQueryParam(nil, "cursor", "c"); len(got) != 1 || got[0].value != "c" {
		t.Fatal(got)
	}
}

func TestModuleVersion(t *testing.T) {
	dependency := &debug.BuildInfo{Main: debug.Module{Path: "example.com/app"}, Deps: []*debug.Module{{Path: modulePath, Version: "v3.1.2"}}}
	if moduleVersion(dependency) != "3.1.2" {
		t.Fatal(moduleVersion(dependency))
	}
	replaced := &debug.BuildInfo{Deps: []*debug.Module{{Path: modulePath, Version: "v3.1.2", Replace: &debug.Module{Path: "../lettermint-go"}}}}
	if moduleVersion(replaced) != "dev" {
		t.Fatal(moduleVersion(replaced))
	}
	local := &debug.BuildInfo{Main: debug.Module{Path: modulePath, Version: "(devel)"}}
	if moduleVersion(local) != "dev" || moduleVersion(&debug.BuildInfo{}) != "dev" {
		t.Fatal("dev")
	}
	if !regexp.MustCompile(`^lettermint-go/(dev|\d+\.\d+\.\d+.*) \(go.+\)$`).MatchString(userAgent()) {
		t.Fatal(userAgent())
	}
}

// The generated files must keep the generator header; regenerate them with
// scripts/generate.sh instead of editing them.
func TestGeneratedFilesKeepTheirHeader(t *testing.T) {
	var headers []string
	for _, name := range []string{"generated_types.go", "generated_operations.go"} {
		file, err := os.Open(name)
		if err != nil {
			t.Fatal(err)
		}
		scanner := bufio.NewScanner(file)
		var lines []string
		for i := 0; i < 5 && scanner.Scan(); i++ {
			lines = append(lines, scanner.Text())
		}
		_ = file.Close()
		patterns := []string{
			`^// Code generated by lettermint/sdk-generator\. DO NOT EDIT\.$`,
			`^// Spec: lettermint/lettermint@[0-9a-f]{40}( \(.+\))?$`,
			`^// sending-openapi\.json SHA-256: [0-9a-f]{64}$`,
			`^// team-openapi\.json SHA-256: [0-9a-f]{64}$`,
			`^// Naming profile: next$`,
		}
		for i, pattern := range patterns {
			if i >= len(lines) || !regexp.MustCompile(pattern).MatchString(lines[i]) {
				t.Fatalf("%s: line %d does not match %s", name, i+1, pattern)
			}
		}
		headers = append(headers, lines[1]+lines[2]+lines[3])
	}
	if headers[0] != headers[1] {
		t.Fatal("the generated files come from different specs")
	}
}

func TestOpenEnumsKeepUnknownValues(t *testing.T) {
	var message MessageData
	if err := json.Unmarshal([]byte(`{"id":"m","status":"brand_new_status","type":"carrier_pigeon"}`), &message); err != nil {
		t.Fatal(err)
	}
	if message.Status != "brand_new_status" || message.Type != "carrier_pigeon" {
		t.Fatalf("%+v", message)
	}
	data, _ := json.Marshal(WebhookPayload{Event: "message.future"})
	if string(data) != `{"id":"","event":"message.future","timestamp":"","data":null}` {
		t.Fatal(string(data))
	}
}
