#!/bin/sh
# Regenerates (or, with --check, verifies) generated_types.go and
# generated_operations.go with the private lettermint/sdk-generator.
# Set LETTERMINT_SDK_GENERATOR to its checkout (default: ../sdk-generator
# next to this repository).
#
# Without the generator (CI, contributors without access), --check only
# verifies that both files carry the generator header with the spec commit
# and hashes, so that hand edits that drop the header are caught.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
generator=${LETTERMINT_SDK_GENERATOR:-$root/../sdk-generator}
check=""
if [ "${1:-}" = "--check" ]; then
	check="--check"
fi

if [ -d "$generator/lettermint_sdkgen" ] && [ -f "$generator/spec.next.lock.json" ]; then
	cd "$generator"
	exec python3 -m lettermint_sdkgen emit go --profile next --lock spec.next.lock.json --out "$root" $check
fi

if [ -z "$check" ]; then
	echo "The SDK generator was not found at $generator. Set LETTERMINT_SDK_GENERATOR to its checkout." >&2
	exit 1
fi

first=""
for name in generated_types.go generated_operations.go; do
	header=$(head -n 5 "$root/$name")
	if ! printf '%s\n' "$header" | awk '
		NR == 1 && $0 != "// Code generated by lettermint/sdk-generator. DO NOT EDIT." { bad = 1 }
		NR == 2 && $0 !~ /^\/\/ Spec: lettermint\/lettermint@[0-9a-f]{40}( \(.+\))?$/ { bad = 1 }
		NR == 3 && $0 !~ /^\/\/ sending-openapi\.json SHA-256: [0-9a-f]{64}$/ { bad = 1 }
		NR == 4 && $0 !~ /^\/\/ team-openapi\.json SHA-256: [0-9a-f]{64}$/ { bad = 1 }
		NR == 5 && $0 != "// Naming profile: next" { bad = 1 }
		END { exit (bad || NR != 5) }'; then
		echo "$name is missing the generator header. Regenerate it; do not edit it by hand." >&2
		exit 1
	fi
	if [ -z "$first" ]; then
		first=$header
	elif [ "$first" != "$header" ]; then
		echo "generated_types.go and generated_operations.go come from different specs. Regenerate both." >&2
		exit 1
	fi
done
echo "SDK generator not found at $generator; checked the generated headers only."
printf '%s\n' "$first" | sed -n 2p
